# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    prefer_relative_imports: true
    sort_pub_dependencies: false

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"