# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    prefer_relative_imports: true
    sort_pub_dependencies: false

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"