name: teigi_app
description: A new Flutter project.

version: 1.0.0+3

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations: 
    sdk: flutter

  app_tracking_transparency: ^2.0.4
  auto_route: ^7.8.3
  cached_network_image: ^3.3.0
  change_app_package_name: ^1.1.0
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  device_info_plus: ^9.1.0
  easy_refresh: ^3.3.2+1
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.3
  fluttertoast: ^8.2.3
  freezed_annotation: ^2.4.1
  google_mobile_ads: ^3.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  in_app_review: ^2.0.8
  intl: ^0.18.1
  keyboard_actions: ^4.2.0
  like_button: ^2.0.5
  mockito: ^5.4.2
  package_info_plus: ^4.2.0
  pull_down_button: ^0.9.3
  riverpod_annotation: ^2.2.0
  roggle: ^0.4.2+1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.1
  version: ^3.0.2

  # Firebase関連
  cloud_firestore: ^4.9.2
  firebase_analytics: ^10.5.1
  firebase_app_check: ^0.1.5
  firebase_auth: 4.10.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_storage: ^11.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  cider: ^0.2.4
  custom_lint: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.3+1
  freezed: ^2.4.1
  pedantic_mono: ^1.24.0+1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:

  uses-material-design: true

  fonts:
  - family: LINESeedJP
    fonts:
      - asset: assets/fonts/LINESeedJP_A_OTF_Th.otf
        weight: 100
      - asset: assets/fonts/LINESeedJP_A_OTF_Rg.otf
        weight: 400
      - asset: assets/fonts/LINESeedJP_A_OTF_Bd.otf
        weight: 700
      - asset: assets/fonts/LINESeedJP_A_OTF_Eb.otf
        weight: 800

  assets:
    - assets/images/introduction_icon/
    - .env

flutter_launcher_icons:
  android: true
  ios: true

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/images/splash/splash.png'
  color_dark: '#000000'
  image_dark: 'assets/images/splash/splash_dark.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/images/splash/splash.png'
    icon_background_color_dark: '#000000'
    image_dark: 'assets/images/splash/splash_dark.png'