name: teigi_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.3
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.3
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.2.0

  # Firebase関連
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  freezed: ^2.4.3
  pedantic_mono: ^1.24.0+1
  riverpod_generator: ^2.3.3

flutter:

  uses-material-design: true
